"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Lock, PlayCircle, Sparkles, Trophy } from "lucide-react";
import { chapters, lessons } from "@/lib/sql-quest/catalog";
import { useSqlProgress } from "./useSqlProgress";

export default function CatalogClient() {
  const { completedCount, totalLessons, totalXP, progressPercent, isCompleted, isUnlocked } = useSqlProgress();
  const nextLesson = lessons.find((lesson) => isUnlocked(lesson.chapter, lesson.lesson) && !isCompleted(lesson.chapter, lesson.lesson)) ?? lessons[0];
  return <div className="min-h-screen bg-[var(--surface)] text-[var(--on-surface)]">
    <header className="border-b border-[var(--outline-variant)]/20 bg-[var(--surface-container-low)]/60">
      <div className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><Link href="/sql-quest" className="inline-flex items-center gap-2 text-sm text-[var(--on-surface-variant)] [@media(hover:hover)_and_(pointer:fine)]:hover:text-[var(--primary-text)]"><ArrowLeft className="h-4 w-4" /> SQL Quest</Link><div className="mt-8 flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--primary-text)]">Central de estudos</p><h1 className="mt-2 font-display text-4xl font-bold tracking-tight sm:text-5xl">Sua próxima conquista começa aqui.</h1><p className="mt-3 max-w-xl leading-7 text-[var(--on-surface-variant)]">Uma trilha guiada para praticar SQL sem perder o fio. Siga a ordem, teste suas ideias e desbloqueie o próximo desafio.</p></div><Link href={`/sql-quest/learn/${nextLesson.chapter}/${nextLesson.lesson}`} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[var(--secondary-container)] px-5 py-3.5 text-sm font-bold text-[var(--on-secondary-container)]"><PlayCircle className="h-5 w-5" />{completedCount ? "Continuar estudando" : "Começar agora"}<ArrowRight className="h-4 w-4" /></Link></div></div>
    </header>
    <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8">
      <div className="mb-10 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-lowest)] p-4"><p className="text-2xl font-bold text-[var(--primary-text)]">{completedCount}<span className="text-sm font-normal text-[var(--on-surface-variant)]">/{totalLessons}</span></p><p className="text-xs text-[var(--on-surface-variant)]">lições concluídas</p></div><div className="rounded-2xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-lowest)] p-4"><p className="flex items-center gap-2 text-2xl font-bold text-[var(--secondary)]">{totalXP} <Trophy className="h-5 w-5" /></p><p className="text-xs text-[var(--on-surface-variant)]">XP acumulado</p></div><div className="rounded-2xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-lowest)] p-4"><p className="text-2xl font-bold">{progressPercent}%</p><p className="text-xs text-[var(--on-surface-variant)]">da trilha explorada</p></div></div>
      <div className="space-y-8">{chapters.map((chapter) => { const chapterLessons = lessons.filter((lesson) => lesson.chapter === chapter.number); const done = chapterLessons.filter((lesson) => isCompleted(lesson.chapter, lesson.lesson)).length; return <section key={chapter.number} className="rounded-3xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-low)]/50 p-5 sm:p-7"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[var(--primary-10)] font-display text-xl font-bold text-[var(--primary-text)]">{chapter.number}</span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--on-surface-variant)]">Capítulo {chapter.number}</p><h2 className="mt-1 text-2xl font-bold">{chapter.title}</h2><p className="mt-1 text-sm text-[var(--on-surface-variant)]">{chapter.description}</p></div></div><span className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--secondary)]"><Sparkles className="h-4 w-4" /> {done}/{chapterLessons.length} concluídas</span></div><ol className="grid gap-3 md:grid-cols-2">{chapterLessons.map((lesson) => { const complete = isCompleted(lesson.chapter, lesson.lesson); const unlocked = isUnlocked(lesson.chapter, lesson.lesson); return <li key={lesson.id}><Link href={unlocked ? `/sql-quest/learn/${lesson.chapter}/${lesson.lesson}` : "#"} aria-disabled={!unlocked} onClick={(event) => !unlocked && event.preventDefault()} className={`group flex min-h-[88px] items-center gap-4 rounded-2xl border p-4 transition [@media(hover:hover)_and_(pointer:fine)]:hover:-translate-y-0.5 ${complete ? "border-emerald-500/30 bg-emerald-500/5" : unlocked ? "border-[var(--outline-variant)]/35 bg-[var(--surface-container-lowest)] [@media(hover:hover)_and_(pointer:fine)]:hover:border-[var(--primary)]/50" : "cursor-not-allowed border-[var(--outline-variant)]/20 bg-[var(--surface-container-low)]/40 opacity-55"}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--surface-container-high)] text-sm font-bold text-[var(--on-surface-variant)]">{complete ? <CheckCircle2 className="h-5 w-5 text-emerald-400" /> : unlocked ? <PlayCircle className="h-5 w-5 text-[var(--primary-text)]" /> : <Lock className="h-4 w-4" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{lesson.title}</span><span className="mt-1 block truncate text-xs text-[var(--on-surface-variant)]">{complete ? "Concluído" : unlocked ? lesson.summary : "Complete a lição anterior para desbloquear"}</span></span><span className="hidden text-xs font-bold text-[var(--secondary)] sm:block">{complete ? "feito" : `${lesson.xpReward} XP`}</span></Link></li>; })}</ol></section>; })}</div>
    </main>
  </div>;
}
