"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Check, Clock3, Coins, Gift, PackageCheck, ShieldCheck, ShoppingBag, X, Zap } from "lucide-react";
import { useAuth } from "@/components/AuthProvider";
import { authedFetch } from "@/lib/client-auth";

type RewardItem = { id: string; name: string; description: string; costXp: number; initialStock: number; remainingStock: number; requestStatus: string | null };
type RewardsResponse = { earnedXp: number; spentXp: number; xpBalance: number; items: RewardItem[] };
type RewardRequest = { id: string; itemId?: string; itemName?: string; studentName?: string; costXp?: number; item?: { name?: string; costXp?: number }; requestDetails: string; status: string; createdAt?: string; updatedAt?: string };

const productNotes: Record<string, string> = {
  "chaveiro simples": "Máximo de 1 por aluno · 5 unidades globais",
  "peça de personagem": "1 unidade global",
  "objeto personalizado até 12 cm": "1 unidade global",
};

function getProductNote(item: RewardItem) {
  const name = item.name.toLocaleLowerCase("pt-BR");
  const id = item.id.toLocaleLowerCase();
  if (productNotes[name]) return productNotes[name];
  if ((id.includes("objeto") || id.includes("custom") || id.includes("personal")) && (id.includes("12") || name.includes("12 cm") || name.includes("objeto"))) return "1 unidade global";
  if (name.includes("objeto") && name.includes("12 cm")) return "1 unidade global";
  return undefined;
}

function useApi<T>(url: string) {
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await authedFetch(url); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Não foi possível carregar os dados."); setData(body); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar os dados."); }
    finally { setLoading(false); }
  }, [url]);
  useEffect(() => { void load(); }, [load]);
  return { data, error, loading, reload: load };
}

function Page({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-[var(--surface)] px-5 py-10 text-[var(--on-surface)] sm:px-8"><div className="mx-auto max-w-6xl">{children}</div></div>; }
function Gate({ children }: { children: React.ReactNode }) { const { user, loading } = useAuth(); if (loading) return <Page><Loading label="Verificando sua conta..." /></Page>; if (!user) return <Page><div className="mx-auto max-w-md rounded-3xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-low)] p-8 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-[var(--primary-text)]" /><h1 className="mt-5 text-2xl font-bold">Entre para acessar a loja</h1><p className="mt-2 text-sm leading-6 text-[var(--on-surface-variant)]">Recompensas e pedidos ficam disponíveis apenas para contas autenticadas.</p><Link href="/login" className="mt-6 inline-flex rounded-xl bg-[var(--secondary-container)] px-5 py-3 text-sm font-bold text-[var(--on-secondary-container)]">Fazer login</Link></div></Page>; return <>{children}</>; }
function Loading({ label = "Carregando..." }: { label?: string }) { return <div className="rounded-3xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-low)] p-12 text-center" role="status" aria-live="polite"><div className="mx-auto h-7 w-7 animate-spin motion-reduce:animate-none rounded-full border-2 border-[var(--primary)] border-t-transparent" /><p className="mt-4 text-sm text-[var(--on-surface-variant)]">{label}</p></div>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="rounded-3xl border border-red-400/30 bg-red-500/5 p-8 text-center" role="alert"><p className="font-semibold text-red-300">{message}</p><button type="button" onClick={retry} className="mt-4 rounded-lg border border-[var(--outline-variant)] px-4 py-2 text-sm font-semibold [@media(hover:hover)_and_(pointer:fine)]:hover:bg-[var(--surface-container-high)]">Tentar novamente</button></div>; }
function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="mb-9"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--primary-text)]">{eyebrow}</p><h1 className="mt-2 font-display text-4xl font-bold tracking-tight sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl leading-7 text-[var(--on-surface-variant)]">{description}</p></div><Link href="/sql-quest" className="text-sm font-semibold text-[var(--on-surface-variant)] [@media(hover:hover)_and_(pointer:fine)]:hover:text-[var(--primary-text)]">← Voltar à trilha</Link></div><nav aria-label="Área do aluno" className="mt-7 flex flex-wrap gap-2 text-sm"><Link href="/sql-quest/profile" className="rounded-full border border-[var(--outline-variant)]/35 px-4 py-2">Perfil</Link><Link href="/sql-quest/loja" className="rounded-full border border-[var(--primary)]/50 bg-[var(--primary-10)] px-4 py-2 font-semibold">Loja</Link><Link href="/sql-quest/achievements" className="rounded-full border border-[var(--outline-variant)]/35 px-4 py-2">Conquistas</Link></nav></header>; }

function formatDate(value?: string) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleDateString("pt-BR"); }
function statusLabel(status: string) { return ({ requested: "Aguardando aprovação", pending: "Aguardando aprovação", approved: "Aprovado", rejected: "Recusado", fulfilled: "Entregue" } as Record<string, string>)[status] || status; }
function statusStyle(status: string) { return status === "approved" ? "text-sky-300 bg-sky-400/10" : status === "fulfilled" ? "text-emerald-300 bg-emerald-400/10" : status === "rejected" ? "text-red-300 bg-red-400/10" : "text-[var(--secondary)] bg-[var(--secondary)]/10"; }

function Balance({ data }: { data: RewardsResponse }) { return <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--secondary)]/30 bg-[var(--secondary)]/5 p-5"><Coins className="h-5 w-5 text-[var(--secondary)]" /><p className="mt-3 text-2xl font-bold text-[var(--secondary)]">{data.xpBalance} XP</p><p className="mt-1 text-xs text-[var(--on-surface-variant)]">XP disponível</p></div><div className="rounded-2xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-low)] p-5"><Zap className="h-5 w-5 text-[var(--primary-text)]" /><p className="mt-3 text-2xl font-bold">{data.earnedXp} XP</p><p className="mt-1 text-xs text-[var(--on-surface-variant)]">XP conquistado</p></div><div className="rounded-2xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-low)] p-5"><ShoppingBag className="h-5 w-5 text-[var(--primary-text)]" /><p className="mt-3 text-2xl font-bold">{data.spentXp} XP</p><p className="mt-1 text-xs text-[var(--on-surface-variant)]">XP utilizado</p></div></div>; }

function RewardCard({ item, balance, selected, onSelect }: { item: RewardItem; balance: number; selected: boolean; onSelect: () => void }) {
  const soldOut = item.remainingStock <= 0;
  const noBalance = balance < item.costXp;
  const requested = Boolean(item.requestStatus);
  const disabled = soldOut || noBalance || requested;
  const note = getProductNote(item);
  return <article className={`flex flex-col rounded-3xl border p-6 ${disabled ? "border-[var(--outline-variant)]/25 bg-[var(--surface-container-low)]/60" : "border-[var(--outline-variant)]/40 bg-[var(--surface-container-lowest)]"}`}><div className="flex items-start justify-between gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--primary-10)] text-[var(--primary-text)]"><Gift className="h-6 w-6" /></span><span className="text-right text-sm font-bold text-[var(--secondary)]">{item.costXp} XP</span></div><h2 className="mt-6 text-xl font-bold">{item.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-[var(--on-surface-variant)]">{item.description}</p>{note && <p className="mt-4 text-xs font-semibold text-[var(--on-surface-variant)]">{note}</p>}<p className="mt-4 text-xs text-[var(--on-surface-variant)]">{item.remainingStock} de {item.initialStock} disponíveis</p><div className="mt-auto pt-5">{soldOut ? <p className="rounded-xl bg-[var(--surface-container-high)] px-4 py-3 text-center text-sm font-bold text-[var(--outline)]">Esgotado</p> : requested ? <p className="rounded-xl bg-[var(--primary-10)] px-4 py-3 text-center text-sm font-bold text-[var(--primary-text)]">Pedido já realizado · {statusLabel(item.requestStatus!)}</p> : noBalance ? <p className="rounded-xl bg-[var(--surface-container-high)] px-4 py-3 text-center text-sm font-bold text-[var(--outline)]">Saldo insuficiente</p> : <button type="button" onClick={onSelect} aria-expanded={selected} className="w-full rounded-xl bg-[var(--secondary-container)] px-4 py-3 text-sm font-bold text-[var(--on-secondary-container)] transition [@media(hover:hover)_and_(pointer:fine)]:hover:-translate-y-0.5">{selected ? "Fechar formulário" : "Pedir recompensa"}</button>}</div></article>;
}

function RequestForm({ item, onDone }: { item: RewardItem; onDone: () => Promise<void> }) { const [details, setDetails] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await authedFetch("/api/sql-quest/rewards/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: item.id, requestDetails: details.trim() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Não foi possível enviar o pedido."); setMessage("Pedido enviado. Aguarde a aprovação do instrutor."); setDetails(""); await onDone(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Não foi possível enviar o pedido."); } finally { setSaving(false); } }; return <form onSubmit={submit} className="mt-4 rounded-2xl border border-[var(--secondary)]/25 bg-[var(--secondary)]/5 p-5"><label htmlFor={`details-${item.id}`} className="text-sm font-bold">Descreva seu pedido</label><p className="mt-1 text-xs leading-5 text-[var(--on-surface-variant)]">Explique como você gostaria da recompensa. São obrigatórios de 3 a 500 caracteres.</p><textarea id={`details-${item.id}`} required minLength={3} maxLength={500} value={details} onChange={(event) => setDetails(event.target.value)} rows={4} className="mt-4 w-full resize-y rounded-xl border border-[var(--outline-variant)]/50 bg-[var(--surface)] px-3 py-2 text-sm outline-none focus:border-[var(--primary)]" placeholder="Ex.: quero o chaveiro com..." /><p className="mt-2 text-right text-xs text-[var(--on-surface-variant)]">{details.length}/500</p><p className="mt-3 text-xs leading-5 text-[var(--on-surface-variant)]">Seu XP só será debitado depois da aprovação do instrutor. Este pedido não reserva estoque.</p>{message && <p className="mt-3 text-sm font-semibold" role="status">{message}</p>}<button type="submit" disabled={saving || details.trim().length < 3} className="mt-4 rounded-xl bg-[var(--secondary-container)] px-4 py-2.5 text-sm font-bold text-[var(--on-secondary-container)] disabled:cursor-not-allowed disabled:opacity-50">{saving ? "Enviando..." : "Enviar pedido"}</button></form>; }

export function RewardsStoreClient() { const { data, error, loading, reload } = useApi<RewardsResponse>("/api/sql-quest/rewards"); const [selected, setSelected] = useState<string | null>(null); if (loading) return <Gate><Page><Loading label="Abrindo a loja..." /></Page></Gate>; return <Gate><Page><Header eyebrow="Recompensas" title="Loja SQL Quest" description="Troque o XP da sua jornada por recompensas. Escolha com calma: nenhum pedido debita ou reserva XP antes da aprovação do instrutor." />{error || !data ? <ErrorState message={error || "Não foi possível carregar a loja."} retry={reload} /> : <><Balance data={data} /><div className="mt-9 grid gap-5 lg:grid-cols-3">{data.items.map((item) => <div key={item.id}><RewardCard item={item} balance={data.xpBalance} selected={selected === item.id} onSelect={() => setSelected(selected === item.id ? null : item.id)} />{selected === item.id && <RequestForm item={item} onDone={async () => { await reload(); setSelected(null); }} />}</div>)}</div><div className="mt-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--outline-variant)]/25 bg-[var(--surface-container-low)] p-5 text-sm"><p className="flex items-center gap-2 text-[var(--on-surface-variant)]"><Clock3 className="h-4 w-4 text-[var(--secondary)]" /> Acompanhe seus pedidos e o andamento da aprovação.</p><Link href="/sql-quest/loja/pedidos" className="font-bold text-[var(--primary-text)]">Ver meus pedidos →</Link></div></>}</Page></Gate>; }

function requestName(request: RewardRequest) { return request.itemName || request.item?.name || "Recompensa"; }
function RequestList({ requests, staff = false, onAction }: { requests: RewardRequest[]; staff?: boolean; onAction?: (id: string, action: "approve" | "reject" | "fulfill") => Promise<void> }) { if (!requests.length) return <div className="rounded-3xl border border-dashed border-[var(--outline-variant)]/40 p-12 text-center"><PackageCheck className="mx-auto h-9 w-9 text-[var(--outline)]" /><h2 className="mt-4 font-bold">Nenhum pedido por aqui</h2><p className="mt-2 text-sm text-[var(--on-surface-variant)]">{staff ? "Novos pedidos de alunos aparecerão nesta lista." : "Quando você pedir uma recompensa, ela aparecerá aqui."}</p></div>; return <div className="space-y-4">{requests.map((request) => <article key={request.id} className="rounded-3xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-lowest)] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold">{requestName(request)}</h2>{staff && <p className="mt-1 text-sm text-[var(--on-surface-variant)]">Pedido de {request.studentName || "aluno"}</p>}</div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusStyle(request.status)}`}>{statusLabel(request.status)}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[var(--on-surface-variant)]">{request.requestDetails}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--outline-variant)]/20 pt-4 text-xs text-[var(--on-surface-variant)]"><span>{request.costXp || request.item?.costXp ? `${request.costXp || request.item?.costXp} XP` : "Pedido de recompensa"} {formatDate(request.createdAt) && `· ${formatDate(request.createdAt)}`}</span>{staff && onAction && <div className="flex flex-wrap gap-2">{(request.status === "requested" || request.status === "pending") && <><button type="button" onClick={() => void onAction(request.id, "reject")} className="inline-flex items-center gap-1 rounded-lg border border-red-400/30 px-3 py-2 text-xs font-bold text-red-300"><X className="h-3.5 w-3.5" /> Recusar</button><button type="button" onClick={() => void onAction(request.id, "approve")} className="inline-flex items-center gap-1 rounded-lg bg-[var(--secondary-container)] px-3 py-2 text-xs font-bold text-[var(--on-secondary-container)]"><Check className="h-3.5 w-3.5" /> Aprovar</button></>}{request.status === "approved" && <button type="button" onClick={() => void onAction(request.id, "fulfill")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-500/15 px-3 py-2 text-xs font-bold text-emerald-300"><PackageCheck className="h-3.5 w-3.5" /> Marcar entregue</button>}</div>}</div></article>)}</div>; }

function RequestsClient({ staff = false }: { staff?: boolean }) { const endpoint = staff ? "/api/sql-quest/rewards/requests?scope=staff" : "/api/sql-quest/rewards/requests"; const { data, error, loading, reload } = useApi<{ requests: RewardRequest[] }>(endpoint); const [actionError, setActionError] = useState(""); const [working, setWorking] = useState(false); const act = async (id: string, action: "approve" | "reject" | "fulfill") => { setWorking(true); setActionError(""); try { const response = await authedFetch(`/api/sql-quest/rewards/requests/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Não foi possível atualizar o pedido."); await reload(); } catch (caught) { setActionError(caught instanceof Error ? caught.message : "Não foi possível atualizar o pedido."); } finally { setWorking(false); } }; if (loading) return <Page><Loading label="Carregando pedidos..." /></Page>; return <Page><Header eyebrow={staff ? "Gestão" : "Recompensas"} title={staff ? "Pedidos de recompensas" : "Meus pedidos"} description={staff ? "Revise os pedidos dos alunos e acompanhe cada etapa até a entrega." : "Acompanhe a aprovação do instrutor e a entrega das suas recompensas."} />{error || !data ? <ErrorState message={error || "Não foi possível carregar os pedidos."} retry={reload} /> : <>{actionError && <div className="mb-5 rounded-2xl border border-red-400/30 bg-red-500/5 p-4 text-sm font-semibold text-red-300" role="alert">{actionError}</div>}{working && <p className="mb-5 text-sm text-[var(--on-surface-variant)]" role="status">Atualizando pedido...</p>}<RequestList requests={data.requests || []} staff={staff} onAction={staff ? act : undefined} /></>}</Page>; }

export function RewardOrdersClient() { return <Gate><RequestsClient /></Gate>; }
export function InstructorRewardOrdersClient() { const { isStaff, loading } = useAuth(); if (loading) return <Page><Loading label="Verificando permissão..." /></Page>; if (!isStaff) return <Gate><Page><div className="rounded-3xl border border-[var(--outline-variant)]/30 bg-[var(--surface-container-low)] p-10 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-[var(--primary-text)]" /><h1 className="mt-5 text-2xl font-bold">Área de instrutor</h1><p className="mt-2 text-sm text-[var(--on-surface-variant)]">Esta área está disponível apenas para instrutores e administradores.</p></div></Page></Gate>; return <Gate><RequestsClient staff /></Gate>; }
